### ISSUE TITLE
Uncaught TypeError: editor.outermostFoldsInBufferRowRange is not a function

### ISSUE THREAD

**Issue by kachkaev** [harai/duplicate-lines-upward#4]
Hi Harai,

I've been enjoying your package for a while, but started getting this after upgrading to 1.9(.6).

![screen shot 2016-08-07 at 10 03 48](https://cloud.githubusercontent.com/assets/608862/17461526/d925f878-5c87-11e6-9c63-86db1c9a2481.png)

Nothing specific needs to be done to catch an exception, I just type some stuff in a new file and then press `alt-cmd-up` as before:

The keymap is the following:
```cson
'atom-workspace atom-text-editor:not([mini])':
  'alt-cmd-up': 'duplicate-lines-upward:duplicate-lines-upward'
```

**Atom Version**: 1.9.6
**System**: Mac OS X 10.11.6
**Thrown From**: [duplicate-lines-upward](https://github.com/harai/duplicate-lines-upward) package, v1.1.2

### Stack Trace

Uncaught TypeError: editor.outermostFoldsInBufferRowRange is not a function

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:852

TypeError: editor.outermostFoldsInBufferRowRange is not a function
    at /Users/alexander/.atom/packages/duplicate-lines-upward/lib/duplicate-lines-upward.coffee:21:18
    at TextBuffer.module.exports.TextBuffer.transact (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:847:18)
    at TextEditor.module.exports.TextEditor.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:1390:26)
    at Object.module.exports.duplicateLinesUpward (/Users/alexander/.atom/packages/duplicate-lines-upward/lib/duplicate-lines-upward.coffee:10:12)
    at atom-workspace.<anonymous> (/Users/alexander/.atom/packages/duplicate-lines-upward/lib/duplicate-lines-upward.coffee:3:94)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:10.4.0 application:new-file (atom-pane.pane.active)
     -0:07.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:06.6.0 core:backspace (atom-text-editor.editor.is-focused)
  3x -0:05.9.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -0:03.2.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:01.6.0 editor:move-line-up (atom-text-editor.editor.is-focused)
     -0:00.6.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:00.0 duplicate-lines-upward:duplicate-lines-upward (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "closeEmptyWindows": false,
    "disabledPackages": [
      "metrics",
      "linter-jscs",
      "markdown-preview",
      "markdown-scroll-sync"
    ],
    "openEmptyEditorOnStart": false,
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
activate-power-mode, v0.7.3 (active)
atom-beautify, v0.29.10 (inactive)
autocomplete-php, v0.3.7 (active)
autocomplete-plus, v2.31.1 (active)
color-picker, v2.2.2 (active)
duplicate-lines-upward, v1.1.2 (inactive)
editorconfig, v1.4.1 (active)
file-icons, v1.7.18 (active)
goto-last-edit, v0.3.2 (active)
linter, v1.11.15 (active)
linter-eslint, v7.2.4 (active)
linter-js-yaml, v1.2.5 (active)
linter-less, v2.6.0 (active)
linter-markdown, v1.5.2 (active)
linter-stylelint, v3.1.0 (active)
markdown-preview-enhanced, v0.8.0 (active)
markdown-scroll-sync, v2.1.2 (inactive)
minimap, v4.24.7 (active)
open-recent, v5.0.0 (active)
php-hyperclick, v1.0.0 (active)
php-twig, v4.0.0 (active)
pigments, v0.31.2 (active)
project-manager, v2.9.7 (active)
react, v0.15.0 (active)
terminal-plus, v0.14.5 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.51.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.43.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.3.2 (inactive)
one-light-ui, v1.3.2 (inactive)
one-dark-syntax, v1.2.0 (inactive)
one-light-syntax, v1.2.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.2 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.1 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.0 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.38.3 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
find-and-replace, v0.198.0 (inactive)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.0 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (inactive)
metrics, v0.53.1 (inactive)
notifications, v0.64.1 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.238.0 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.46.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.98.0 (active)
timecop, v0.33.1 (active)
tree-view, v0.208.0 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.32.2 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.0 (active)
language-csharp, v0.12.1 (active)
language-css, v0.36.2 (active)
language-gfm, v0.86.0 (active)
language-git, v0.13.0 (active)
language-go, v0.42.0 (active)
language-html, v0.44.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.22.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.0 (active)
language-less, v0.29.3 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.0 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.68.5 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.52.0 (active)
language-shellscript, v0.22.3 (active)
language-source, v0.9.0 (active)
language-sql, v0.21.1 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.8 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

Who else can see that?
